### ISSUE TITLE
Remove default value for username

### ISSUE THREAD

**Issue by edubxb** [pmazurek/aws-fuzzy-finder#14]
Having a default value for the username don't allows to use the ssh_config file (`~/.ssh/config`) to specify the username used to connect to the instances.

**Comment by pmazurek** [comment]
Fair point, I'll fix it.

**Comment by axitkhurana** [comment]
@pmazurek Thanks for the project! I agree with @edubxb would be awesome if the library would let it use ssh_config values by default. Let me know if you'd like a PR on this.

**Comment by rszalski** [comment]
I think I can speak for @pmazurek that we welcome all PRs, so feel free to submit one!

**Comment by pmazurek** [comment]
Fixed
