### ISSUE TITLE
Cache feature is not working 

### ISSUE THREAD

**Issue by RahulGupta-Reflektion** [pmazurek/aws-fuzzy-finder#18]
After setting up required variables in ~/.bashrc  on MacOS Sierra 
```
$ echo  $AWS_FUZZ_USE_CACHE
yes
$ echo $AWS_FUZZ_CACHE_EXPIRY
3600

```

it doesn't populate `~/.aws_fuzzy_finder.cache` file. instead there is another file `~/.aws_fuzzy_finder.cache.db`. Not sure if this was intended. 

This might be one of the reason.
https://github.com/jlee-made/aws-fuzzy-finder/commit/062cc391ebdda85ea221a2da931fae3422bf85d1

**Comment by pmazurek** [comment]
OK, fixed in #19 , thank you for your contribution @RahulGupta-Reflektion , cheers.
