### ISSUE TITLE
On OSX doesn't work

### ISSUE THREAD

**Issue by palankai** [pmazurek/aws-fuzzy-finder#2]
Tested on:
OSX El Captain (10.11.4)
2.2 GHz Intel Core i7
Python 2.7.11
pip 8.0.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

```
$ aws-fuzzy
/bin/bash: line 12: /usr/local/lib/python2.7/site-packages/aws_fuzzy_finder/fzf-0.12.1-linux_386: cannot execute binary file
```

**Comment by pmazurek** [comment]
Fixed in https://github.com/pmazurek/aws-fuzzy-finder/commit/44ca60805f863b81e6ef381511c345b3714b99b2
