### ISSUE TITLE
Error detecting Linux platform

### ISSUE THREAD

**Issue by fmariluis** [pmazurek/aws-fuzzy-finder#3]
I run Ubuntu 16.04, but aws-fuzzy fails with:

`Currently only MAC OS and Linux are supported, exiting.`

The problem is here:
```python
 if sys.platform == 'linux2':
        lib = 'fzf-0.12.1-linux_386'
    elif sys.platform == 'darwin':
        lib = 'fzf-0.12.1-darwin_386'
    else:
        print('Currently only MAC OS and Linux are supported, exiting.')
        exit(1)
```

In my case (and I assume many others as well) the output of sys.platform is this:

```
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'linux'
```

Fix seems trivial.
Thanks for your work!

**Comment by pmazurek** [comment]
Ah, there seems to be a difference in sys.platform in python3 vs python2 https://docs.python.org/3/library/sys.html#sys.platform

Thank you for your contribution, I'll push a fix in a bit.

**Comment by pmazurek** [comment]
Fixed in https://github.com/pmazurek/aws-fuzzy-finder/commit/686b322a6b9fd1c30b1269e4455050b9ef2487f6, grab the latest version (0.3.2).
