### ISSUE TITLE
aws-fuzzy-finder broken in MacOS Monterey

### ISSUE THREAD

**Issue by jstuber-togetherwork** [pmazurek/aws-fuzzy-finder#43]
MacOS Monterey completely breaks aws-fuzzy-finder:
`Exception occurred while getting cache, getting instances from AWS api: db type is dbm.gnu, but the module is not available
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x1163384, 0x21)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff7b0 sp=0x7ff7bfeff790 pc=0x1028105
runtime.goenvs()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff7e0 sp=0x7ff7bfeff7b0 pc=0x10259a3
runtime.schedinit()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go:482 +0xa1 fp=0x7ff7bfeff820 sp=0x7ff7bfeff7e0 pc=0x102aab1
runtime.rt0_go(0x7ff7bfeff850, 0x1, 0x7ff7bfeff850, 0x1000000, 0x1, 0x7ff7bfeffa38, 0x0, 0x7ff7bfeffaa2, 0x7ff7bfeffab9, 0x7ff7bfeffacd, ...)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff828 sp=0x7ff7bfeff820 pc=0x105285b`

An investigation online reveals that this issue is related to the app being built in an earlier version of Go, which is no longer compatible with MacOS Monterery, the recommendation from Go is to rebuild the app with a newer version of Go. https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue

**Comment by epoplavskis** [comment]
got it fixed in here -> https://github.com/pmazurek/aws-fuzzy-finder/pull/44

**Comment by palankai** [comment]
Fixed in the latest release v1.1.2
